const notes = [
  {
    id: 1,
    title: "React Basics",
    content: "Learn about components, props, and state management.",
    category: "Programming",
    date: "2025-09-29",
    pinned: false,
    tags: ["react", "frontend", "javascript"],
  },
  {
    id: 2,
    title: "Express.js Setup",
    content: "Initialize a project with npm and install Express for backend.",
    category: "Backend",
    date: "2025-09-28",
    pinned: true,
    tags: ["node", "express", "api"],
  },
  {
    id: 3,
    title: "Workout Plan",
    content: "Push day: Bench press, shoulder press, triceps dips.",
    category: "Fitness",
    date: "2025-09-27",
    pinned: false,
    tags: ["health", "gym", "strength"],
  },
  {
    id: 4,
    title: "Grocery List",
    content: "Milk, bread, eggs, rice, lentils, fruits.",
    category: "Personal",
    date: "2025-09-26",
    pinned: false,
    tags: ["shopping", "daily", "food"],
  },
  {
    id: 5,
    title: "Project Ideas",
    content: "Build a task manager app with drag-and-drop features.",
    category: "Ideas",
    date: "2025-09-25",
    pinned: true,
    tags: ["side-project", "apps", "creativity"],
  },
  {
    id: 6,
    title: "Books to Read",
    content: "Clean Code, Atomic Habits, Deep Work.",
    category: "Learning",
    date: "2025-09-24",
    pinned: false,
    tags: ["books", "self-improvement"],
  },
  {
    id: 7,
    title: "Meeting Notes",
    content: "Discussed roadmap for Q4, assigned tasks to the dev team.",
    category: "Work",
    date: "2025-09-23",
    pinned: true,
    tags: ["work", "team", "planning"],
  },
  {
    id: 8,
    title: "Recipe Idea",
    content: "Try making homemade pasta with creamy mushroom sauce.",
    category: "Food",
    date: "2025-09-22",
    pinned: false,
    tags: ["cooking", "recipes"],
  },
];

export default notes;
