const  products = [
  {
    name: "Fruit cream 125 grms",
    quantity: "125 grms",
    price: 80,
    rating: null,
    category: "Fruit cream",
    description: "A mini bowl of fruity delight.",
    image: "Fruit cream 125 grms.jpg",
  },
  {
    name: "Fruit cream 250 grms",
    quantity: "250 grms",
    price: 150,
    rating: null,
    category: "Fruit cream",
    description: "A satisfying scoop of sweet and juicy fruits.",
    image: "Fruit cream 250 grms.jpg",
  },
  {
    name: "Fruit cream 500 grms",
    quantity: "500 grms",
    price: 280,
    rating: 5,
    category: "Fruit cream",
    description: "A bestseller filled with fruit and cream bliss.",
    image: "Fruit cream 500 grms.jpg",
  },
  {
    name: "Fruit cream 1000 grms",
    quantity: "1000 grms",
    price: 540,
    rating: null,
    category: "Fruit cream",
    description: "Enough creamy fruit for the whole family.",
    image: "Fruit cream 1000 grms.jpg",
  },
  {
    name: "Fruit Cream 125 Gms",
    quantity: "Taste of heaven",
    price: 80,
    rating: null,
    category: "Fruit cream",
    description: "Tiny pack, huge burst of creamy fruit joy.",
    image: "Fruit cream 125 grms.jpg",
  },
  {
    name: "Blue Curacao Mojito",
    quantity: "Blue Curacao Mojito",
    price: 80,
    rating: null,
    category: "Mojito Flavoured Drink",
    description: "Cool, vibrant, and tropical blue refreshment.",
    image: "Blue Curacao Mojito.jpg",
  },
  {
    name: "Green Apple Mojito",
    quantity: "Green Apple Mojito",
    price: 80,
    rating: null,
    category: "Mojito Flavoured Drink",
    description: "Tangy apple meets cool mint in a fizzy blend.",
    image: "Green Apple Mojito.jpg",
  },
  {
    name: "Mint Mojito",
    quantity: "Mint Mojito",
    price: 80,
    rating: null,
    category: "Mojito Flavoured Drink",
    description: "A zesty mint blast in every sip.",
    image: "Mint Mojito.jpg",
  },
  {
    name: "Water Melon Mojito",
    quantity: "Water Melon Mojito",
    price: 80,
    rating: null,
    category: "Mojito Flavoured Drink",
    description: "Cool watermelon meets fizzy minty vibes.",
    image: "Water Melon Mojito.jpg",
  },
  {
    name: "Grenadine Mojito",
    quantity: "Grenadine Mojito",
    price: 80,
    rating: null,
    category: "Mojito Flavoured Drink",
    description: "Sweet grenadine with a minty sparkle.",
    image: "Grenadine Mojito.jpg",
  },
  {
    name: "Butter Scotch Shakes",
    quantity: "-",
    price: 80,
    rating: null,
    category: "Flavoured Shakes with Ice Cream",
    description: "Rich, creamy butterscotch in every sip.",
    image: "Butter Scotch Shakes.jpg",
  },
  {
    name: "Chocolate Shake",
    quantity: "-",
    price: 80,
    rating: null,
    category: "Flavoured Shakes with Ice Cream",
    description: "Pure indulgence in every chocolate swirl.",
    image: "Choclate Shakes.jpg",
  },
  {
    name: "Cold Coffee",
    quantity: "-",
    price: 60,
    rating: null,
    category: "Flavoured Shakes with Ice Cream",
    description: "Chilled caffeine to beat the heat.",
    image: "Cold Coffee.jpg",
  },
  {
    name: "Kit Kat Shakes",
    quantity: "-",
    price: 80,
    rating: null,
    category: "Flavoured Shakes with Ice Cream",
    description: "Crunchy Kit Kat meets creamy goodness.",
    image: "Kit Kat Shakes.jpg",
  },
  {
    name: "Mango Shakes",
    quantity: "-",
    price: 80,
    rating: null,
    category: "Flavoured Shakes with Ice Cream",
    description: "Sweet mango blended to smooth perfection.",
    image: "Mango Shakes.jpg",
  },
  {
    name: "Oreo Shakes",
    quantity: "-",
    price: 80,
    rating: null,
    category: "Flavoured Shakes with Ice Cream",
    description: "Crunchy Oreos blended into creamy delight.",
    image: "Oreo Shakes.jpg",
  },
  {
    name: "Strawberry Shakes",
    quantity: "-",
    price: 70,
    rating: null,
    category: "Flavoured Shakes with Ice Cream",
    description: "Fresh strawberries swirled in cream.",
    image: "Strawberry Shakes.jpg",
  },
  {
    name: "Vanila Shakes",
    quantity: "-",
    price: 60,
    rating: null,
    category: "Flavoured Shakes with Ice Cream",
    description: "Smooth, classic vanilla to calm your soul.",
    image: "Vanila Shakes.jpg",
  },
  {
    name: "Red Soda with Milk",
    quantity: "-",
    price: 50,
    rating: null,
    category: "Flavoured Shakes with Ice Cream",
    description: "A bold twist of fizz and dairy fusion.",
    image: "Red Soda with Milk.jpg",
  },
];
export default products;